### ISSUE TITLE
.update is not working

### ISSUE THREAD

**Issue by only-cliches** [jordanstephens/kepler.js#2]
When I try to use the library, the `.update` property doesn't work as expected.

https://codepen.io/clicksimply/pen/QoQJbO

The location property remains the same after `.udpate` is called.

**Comment by malaretv** [comment]
Looking at the source code it seems the `.update` property returns a new instance of Orbit rather than modifying the existing one. So try something like:

``` 
var iss = kepler.default.Orbit.fromParams({ ... });
console.log([...iss.r.elements]);
const issNew = iss.update(60 * 45)
console.log([...issNew.r.elements]);
```

**Comment by only-cliches** [comment]
Excellent!  That works, thank you!
